(() => {
  const gerund = (marked, meaning, translation, role, emphasis = '', focus = '') => ({
    marked, answer: 'gerund', meaning, translation, role, emphasis, focus: focus || emphasis || meaning
  });
  const participle = (marked, meaning, translation, role, focus) => ({
    marked, answer: 'participle', meaning, translation, role, emphasis: '', focus
  });

  window.ING_ITEMS = [
    gerund(`[Reading] books is fun.`, `책을 읽는 것`, `책을 읽는 것은 재미있다.`, `subject`),
    gerund(`[Swimming] is good exercise.`, `수영하는 것`, `수영하는 것은 좋은 운동이다.`, `subject`),
    gerund(`[Getting] enough sleep is important.`, `충분히 자는 것`, `충분히 자는 것은 중요하다.`, `subject`),
    gerund(`[Learning] a foreign language takes time.`, `외국어를 배우는 것`, `외국어를 배우는 데에는 시간이 걸린다.`, `subject`, ``, `외국어를 배우는 데`),
    gerund(`[Walking] every morning keeps me healthy.`, `매일 아침 걷는 것`, `매일 아침 걷는 것은 나를 건강하게 해 준다.`, `subject`),
    gerund(`[Helping] others makes me happy.`, `다른 사람들을 돕는 것`, `다른 사람들을 돕는 것은 나를 행복하게 한다.`, `subject`),
    gerund(`[Taking] pictures is her hobby.`, `사진을 찍는 것`, `사진을 찍는 것은 그녀의 취미이다.`, `subject`),
    gerund(`[Traveling] alone can be exciting.`, `혼자 여행하는 것`, `혼자 여행하는 것은 신나는 일이 될 수 있다.`, `subject`),
    gerund(`[Making] mistakes is part of learning.`, `실수하는 것`, `실수하는 것은 학습의 한 부분이다.`, `subject`),
    gerund(`[Eating] too much sugar is unhealthy.`, `설탕을 너무 많이 먹는 것`, `설탕을 너무 많이 먹는 것은 건강에 좋지 않다.`, `subject`),

    gerund(`I enjoy [listening] to music.`, `음악을 듣는 것`, `나는 음악을 듣는 것을 즐긴다.`, `verb-object`),
    gerund(`She finished [doing] her homework.`, `숙제를 하는 것`, `그녀는 숙제하는 것을 끝냈다.`, `verb-object`, ``, `숙제하는 것`),
    gerund(`He stopped [smoking] last year.`, `담배를 피우는 것`, `그는 작년에 담배 피우는 것을 그만두었다.`, `verb-object`, ``, `담배 피우는 것`),
    gerund(`They avoided [answering] the question.`, `그 질문에 대답하는 것`, `그들은 그 질문에 대답하는 것을 피했다.`, `verb-object`),
    gerund(`We practiced [speaking] English.`, `영어로 말하는 것`, `우리는 영어로 말하는 것을 연습했다.`, `verb-object`),
    gerund(`She suggested [taking] a taxi.`, `택시를 타는 것`, `그녀는 택시를 타는 것을 제안했다.`, `verb-object`),
    gerund(`I don't mind [waiting] here.`, `여기서 기다리는 것`, `나는 여기서 기다리는 것을 꺼리지 않는다.`, `verb-object`),
    gerund(`He gave up [playing] computer games.`, `컴퓨터 게임을 하는 것`, `그는 컴퓨터 게임을 하는 것을 포기했다.`, `verb-object`),
    gerund(`Would you mind [opening] the window?`, `창문을 여는 것`, `창문을 열어 주시겠어요?`, `verb-object`, ``, `창문을 열어`),
    gerund(`They considered [moving] to Seoul.`, `서울로 이사하는 것`, `그들은 서울로 이사하는 것을 고려했다.`, `verb-object`),

    gerund(`Thank you for [helping] me.`, `나를 도와준 것`, `나를 도와주어서 고맙습니다.`, `preposition-object`, ``, `나를 도와주어서`),
    gerund(`She is good at [solving] problems.`, `문제를 해결하는 것`, `그녀는 문제를 해결하는 데 능숙하다.`, `preposition-object`, ``, `문제를 해결하는 데`),
    gerund(`He left without [saying] goodbye.`, `작별 인사를 하는 것`, `그는 작별 인사를 하지 않고 떠났다.`, `preposition-object`, ``, `작별 인사를 하지 않고`),
    gerund(`Brush your teeth before [going] to bed.`, `잠자리에 드는 것`, `잠자리에 들기 전에 이를 닦아라.`, `preposition-object`, ``, `잠자리에 들기`),
    gerund(`I am interested in [learning] French.`, `프랑스어를 배우는 것`, `나는 프랑스어를 배우는 데 관심이 있다.`, `preposition-object`, ``, `프랑스어를 배우는 데`),
    gerund(`They talked about [building] a new library.`, `새 도서관을 짓는 것`, `그들은 새 도서관을 짓는 것에 관해 이야기했다.`, `preposition-object`),
    gerund(`She is afraid of [making] mistakes.`, `실수하는 것`, `그녀는 실수하는 것을 두려워한다.`, `preposition-object`),
    gerund(`He apologized for [being] late.`, `늦은 것`, `그는 늦은 것에 대해 사과했다.`, `preposition-object`),
    gerund(`We look forward to [meeting] you.`, `당신을 만나는 것`, `우리는 당신을 만나기를 기대한다.`, `preposition-object`, ``, `당신을 만나기`),
    gerund(`You can improve by [practicing] every day.`, `매일 연습하는 것`, `매일 연습함으로써 실력을 향상할 수 있다.`, `preposition-object`, ``, `매일 연습함`),

    gerund(`My hobby is [collecting] stamps.`, `우표를 모으는 것`, `내 취미는 우표를 모으는 것이다.`, `complement`),
    gerund(`Her favorite activity is [painting].`, `그림을 그리는 것`, `그녀가 가장 좋아하는 활동은 그림을 그리는 것이다.`, `complement`),
    gerund(`His job is [teaching] young children.`, `어린아이들을 가르치는 것`, `그의 직업은 어린아이들을 가르치는 것이다.`, `complement`),
    gerund(`The hardest part was [finding] the right answer.`, `정답을 찾는 것`, `가장 어려운 부분은 정답을 찾는 것이었다.`, `complement`),
    gerund(`What I like most is [watching] old movies.`, `옛날 영화를 보는 것`, `내가 가장 좋아하는 것은 옛날 영화를 보는 것이다.`, `complement`),

    gerund(`There is no use [worrying] about it.`, `그것을 걱정하는 것`, `그것을 걱정해도 소용없다.`, `fixed-expression`, ``, `그것을 걱정`),
    gerund(`She spent two hours [cleaning] her room.`, `방을 청소하는 데`, `그녀는 방을 청소하는 데 두 시간을 썼다.`, `omitted-preposition`),
    gerund(`He had difficulty [understanding] the instructions.`, `지시 사항을 이해하는 데`, `그는 지시 사항을 이해하는 데 어려움을 겪었다.`, `omitted-preposition`),
    gerund(`It is worth [visiting] the museum.`, `그 박물관을 방문하는 것`, `그 박물관은 방문할 가치가 있다.`, `worth-complement`, ``, `방문할`),
    gerund(`I remember [meeting] him before.`, `전에 그를 만났던 것`, `나는 전에 그를 만났던 것을 기억한다.`, `verb-object`),

    gerund(`a [sleeping] bag`, `잠자는 것에 쓰는`, `잠자는 것에 쓰는 가방`, `noun-purpose`, `잠자는 것`),
    gerund(`a [sleeping] car`, `잠자는 것에 쓰는`, `잠자는 것에 쓰는 객차`, `noun-purpose`, `잠자는 것`),
    gerund(`a [swimming] pool`, `수영하는 것에 쓰는`, `수영하는 것에 쓰는 수영장`, `noun-purpose`, `수영하는 것`),
    gerund(`a [waiting] room`, `기다리는 것에 쓰는`, `기다리는 것에 쓰는 방`, `noun-purpose`, `기다리는 것`),
    gerund(`a [washing] machine`, `세탁하는 것에 쓰는`, `세탁하는 것에 쓰는 기계`, `noun-purpose`, `세탁하는 것`),
    gerund(`a [reading] room`, `책을 읽는 것에 쓰는`, `책을 읽는 것에 쓰는 방`, `noun-purpose`, `책을 읽는 것`),
    gerund(`a [reading] lamp`, `책을 읽는 것에 쓰는`, `책을 읽는 것에 쓰는 램프`, `noun-purpose`, `책을 읽는 것`),
    gerund(`a [parking] lot`, `주차하는 것에 쓰는`, `주차하는 것에 쓰는 공간`, `noun-purpose`, `주차하는 것`),
    gerund(`a [walking] stick`, `걷는 것에 쓰는`, `걷는 것에 쓰는 지팡이`, `noun-purpose`, `걷는 것`),
    gerund(`[running] shoes`, `달리는 것에 쓰는`, `달리는 것에 쓰는 신발`, `noun-purpose`, `달리는 것`),
    gerund(`a [fishing] rod`, `낚시하는 것에 쓰는`, `낚시하는 것에 쓰는 낚싯대`, `noun-purpose`, `낚시하는 것`),
    gerund(`a [fishing] boat`, `낚시하는 것에 쓰는`, `낚시하는 것에 쓰는 배`, `noun-purpose`, `낚시하는 것`),
    gerund(`a [sewing] machine`, `바느질하는 것에 쓰는`, `바느질하는 것에 쓰는 기계`, `noun-purpose`, `바느질하는 것`),
    gerund(`[boxing] gloves`, `권투하는 것에 쓰는`, `권투하는 것에 쓰는 장갑`, `noun-purpose`, `권투하는 것`),
    gerund(`[cooking] oil`, `요리하는 것에 쓰는`, `요리하는 것에 쓰는 기름`, `noun-purpose`, `요리하는 것`),
    gerund(`a [writing] desk`, `글을 쓰는 것에 쓰는`, `글을 쓰는 것에 쓰는 책상`, `noun-purpose`, `글을 쓰는 것`),
    gerund(`a [skating] rink`, `스케이트를 타는 것에 쓰는`, `스케이트를 타는 것에 쓰는 링크`, `noun-purpose`, `스케이트를 타는 것`),
    gerund(`a [shopping] cart`, `쇼핑하는 것에 쓰는`, `쇼핑하는 것에 쓰는 카트`, `noun-purpose`, `쇼핑하는 것`),
    gerund(`a [shopping] bag`, `쇼핑하는 것에 쓰는`, `쇼핑하는 것에 쓰는 가방`, `noun-purpose`, `쇼핑하는 것`),
    gerund(`a [driving] school`, `운전을 배우는 것에 쓰는`, `운전을 배우는 것에 쓰는 학교`, `noun-purpose`, `운전을 배우는 것`),
    gerund(`[drinking] water`, `마시는 것에 쓰는`, `마시는 것에 쓰는 물`, `noun-purpose`, `마시는 것`),
    gerund(`a [drinking] glass`, `물을 마시는 것에 쓰는`, `물을 마시는 것에 쓰는 잔`, `noun-purpose`, `물을 마시는 것`),
    gerund(`a [dining] table`, `식사하는 것에 쓰는`, `식사하는 것에 쓰는 탁자`, `noun-purpose`, `식사하는 것`),
    gerund(`a [changing] room`, `옷을 갈아입는 것에 쓰는`, `옷을 갈아입는 것에 쓰는 방`, `noun-purpose`, `옷을 갈아입는 것`),
    gerund(`a [swimming] cap`, `수영하는 것에 쓰는`, `수영하는 것에 쓰는 모자`, `noun-purpose`, `수영하는 것`),

    participle(`I am [playing] basketball.`, `농구를 하고 있는`, `나는 농구를 하고 있다.`, `progressive`, `하고 있다`),
    participle(`She is [washing] the dishes.`, `설거지를 하고 있는`, `그녀는 설거지를 하고 있다.`, `progressive`, `하고 있다`),
    participle(`They are [building] a new bridge.`, `새 다리를 짓고 있는`, `그들은 새 다리를 짓고 있다.`, `progressive`, `짓고 있다`),
    participle(`The dog is [barking] loudly.`, `크게 짖고 있는`, `그 개는 크게 짖고 있다.`, `progressive`, `짖고 있다`),
    participle(`We were [waiting] for the bus.`, `버스를 기다리고 있는`, `우리는 버스를 기다리고 있었다.`, `progressive`, `기다리고 있었다`),
    participle(`He was [reading] a newspaper.`, `신문을 읽고 있는`, `그는 신문을 읽고 있었다.`, `progressive`, `읽고 있었다`),
    participle(`The children are [swimming] in the pool.`, `수영장에서 수영하고 있는`, `아이들은 수영장에서 수영하고 있다.`, `progressive`, `수영하고 있다`),
    participle(`My brother is [studying] in his room.`, `자기 방에서 공부하고 있는`, `내 남동생은 자기 방에서 공부하고 있다.`, `progressive`, `공부하고 있다`),
    participle(`It is [raining] outside.`, `밖에 비가 오고 있는`, `밖에 비가 오고 있다.`, `progressive`, `비가 오고 있다`),
    participle(`The birds were [singing] in the trees.`, `나무에서 노래하고 있는`, `새들은 나무에서 노래하고 있었다.`, `progressive`, `노래하고 있었다`),

    participle(`a [sleeping] baby`, `자고 있는`, `자고 있는 아기`, `noun-modifier-before`, `자고 있는`),
    participle(`a [barking] dog`, `짖고 있는`, `짖고 있는 개`, `noun-modifier-before`, `짖고 있는`),
    participle(`the [rising] sun`, `떠오르는`, `떠오르는 태양`, `noun-modifier-before`, `떠오르는`),
    participle(`[boiling] water`, `끓고 있는`, `끓고 있는 물`, `noun-modifier-before`, `끓고 있는`),
    participle(`[running] water`, `흐르는`, `흐르는 물`, `noun-modifier-before`, `흐르는`),
    participle(`the girl [wearing] a red hat`, `빨간 모자를 쓰고 있는`, `빨간 모자를 쓰고 있는 소녀`, `noun-modifier-after`, `쓰고 있는`),
    participle(`the man [standing] at the door`, `문 앞에 서 있는`, `문 앞에 서 있는 남자`, `noun-modifier-after`, `서 있는`),
    participle(`the students [waiting] outside`, `밖에서 기다리고 있는`, `밖에서 기다리고 있는 학생들`, `noun-modifier-after`, `기다리고 있는`),
    participle(`the bird [flying] over the lake`, `호수 위를 날고 있는`, `호수 위를 날고 있는 새`, `noun-modifier-after`, `날고 있는`),
    participle(`the woman [carrying] the box`, `상자를 들고 있는`, `상자를 들고 있는 여자`, `noun-modifier-after`, `들고 있는`),
    participle(`the children [playing] in the yard`, `마당에서 놀고 있는`, `마당에서 놀고 있는 아이들`, `noun-modifier-after`, `놀고 있는`),
    participle(`the man [driving] the bus`, `버스를 운전하고 있는`, `버스를 운전하고 있는 남자`, `noun-modifier-after`, `운전하고 있는`),
    participle(`the girl [dancing] on the stage`, `무대에서 춤추고 있는`, `무대에서 춤추고 있는 소녀`, `noun-modifier-after`, `춤추고 있는`),
    participle(`the boy [holding] the umbrella`, `우산을 들고 있는`, `우산을 들고 있는 소년`, `noun-modifier-after`, `들고 있는`),
    participle(`the horse [running] across the field`, `들판을 가로질러 달리고 있는`, `들판을 가로질러 달리고 있는 말`, `noun-modifier-after`, `달리고 있는`),
    participle(`the woman [talking] to Mr. Kim`, `김 선생님과 이야기하고 있는`, `김 선생님과 이야기하고 있는 여자`, `noun-modifier-after`, `이야기하고 있는`),
    participle(`the students [preparing] for the test`, `시험을 준비하고 있는`, `시험을 준비하고 있는 학생들`, `noun-modifier-after`, `준비하고 있는`),
    participle(`the man [repairing] the roof`, `지붕을 수리하고 있는`, `지붕을 수리하고 있는 남자`, `noun-modifier-after`, `수리하고 있는`),
    participle(`the boy [swimming] in the pool`, `수영장에서 수영하고 있는`, `수영장에서 수영하고 있는 소년`, `noun-modifier-after`, `수영하고 있는`),
    participle(`the leaves [falling] from the trees`, `나무에서 떨어지고 있는`, `나무에서 떨어지고 있는 나뭇잎들`, `noun-modifier-after`, `떨어지고 있는`),

    participle(`I saw a boy [crossing] the street.`, `길을 건너고 있는`, `나는 한 소년이 길을 건너고 있는 것을 보았다.`, `object-complement`, `건너고 있는`),
    participle(`We heard someone [knocking] on the door.`, `문을 두드리고 있는`, `우리는 누군가 문을 두드리는 소리를 들었다.`, `object-complement`, `두드리는`),
    participle(`She kept me [waiting] for an hour.`, `한 시간 동안 기다리게`, `그녀는 나를 한 시간 동안 기다리게 했다.`, `object-complement`, `기다리게`),
    participle(`I found him [sleeping] on the sofa.`, `소파에서 자고 있는`, `나는 그가 소파에서 자고 있는 것을 발견했다.`, `object-complement`, `자고 있는`),
    participle(`They watched the children [playing] soccer.`, `축구를 하고 있는`, `그들은 아이들이 축구하는 것을 지켜보았다.`, `object-complement`, `축구하는`),
    participle(`He sat on the sofa [reading] a newspaper.`, `신문을 읽으면서`, `그는 신문을 읽으면서 소파에 앉아 있었다.`, `simultaneous-action`, `읽으면서`),
    participle(`She walked home [singing] a song.`, `노래를 부르면서`, `그녀는 노래를 부르면서 집으로 걸어갔다.`, `simultaneous-action`, `부르면서`),

    participle(`The movie was [exciting].`, `흥미진진한`, `그 영화는 흥미진진했다.`, `adjective-complement`, `흥미진진했다`),
    participle(`The story is [interesting].`, `흥미로운`, `그 이야기는 흥미롭다.`, `adjective-complement`, `흥미롭다`),
    participle(`The result was [surprising].`, `놀라운`, `그 결과는 놀라웠다.`, `adjective-complement`, `놀라웠다`)
  ];
})();
